### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by cuongngosa** [holdenlee/purescript-games#1]
Hi, I'm new with purescript.
May I ask what the game performance belong to ? Browser run as js compiled from purescript compiler so that how can we check or test about performance or optimize on purescript side ?

**Comment by holdenlee** [comment]
You can use the output javascript code with tools that check javascript performance. You can also search for tools to check performance on the purescript side. 

This question is not directly related to the repo; please ask on StackOverflow or a similar site if you'd like further discussion.
