### ISSUE TITLE
can't build master

### ISSUE THREAD

**Issue by danlaudk** [holdenlee/purescript-games#2]
Which version of purs should i be using to  `pulp build` this?
I also tried to use psc-package instead of bower, and when i use `    "set": "psc-0.10.5"    `, I get 52 helpful but tedious syntax errors, related to purs updates, I think. 

And when I used   `     "set": "psc-0.10.4"    `  , I get 

    Package signal does not exist in package set

**Comment by holdenlee** [comment]
I updated the code to build with purs 0.12.1.
