### ISSUE TITLE
Permission to use in the PureScript Cookbook

### ISSUE THREAD

**Issue by milesfrain** [holdenlee/purescript-games#4]
Hi Holden,

Your example and writeup were really helpful for me in learning how to use the Signal library.

I'd like to feature this example in the [PureScript Cookbook](https://github.com/JordanMartinez/purescript-cookbook) (PR https://github.com/JordanMartinez/purescript-cookbook/pull/213) so this will be more discoverable by others.

Let me know if you have any citation preferences. Here's the [current draft](https://github.com/milesfrain/purescript-cookbook/tree/signal-snake-js/recipes/SignalSnakeJs) which credits your work.

**Comment by holdenlee** [comment]
I'm glad that you found it helpful! You have my permission to use the example in the PureScript Cookbook. The citation is good with me.
